# Generated by Django 5.1 on 2024-09-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_post_category_post_tags_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
